Cristian mera redux
GonzaloIvanVallone/Proyecto-Grupal pull request #7
Opened 2022-12-01 01:29 UTC by cristian-mera

2022-12-01 01:34 UTC, DevilishSnake approved these changes

2022-12-01 02:36 UTC, GonzaloIvanVallone commented on proyecto-grupal/client/src/redux/reducer/productsReducer.js
> +        videogames: action.payload,
que es videogames? jajaja

2022-12-01 02:37 UTC, GonzaloIvanVallone requested changes
fijate en el ultimo archivo modificado te deje un comentario, se esta haciendo llamada a un estado que no existe

2022-12-01 09:29 UTC, Brunoliserre commented on proyecto-grupal/client/src/redux/actions/productsActions.js
> +          `https://dummyjson.com/products/search?q=${name}`
No debería llamar a localhost?

2022-12-03 00:51 UTC, cristian-mera commented on proyecto-grupal/client/src/redux/actions/productsActions.js
> +          `https://dummyjson.com/products/search?q=${name}`
estaba llamando a la api para probarlo, pero finalmente el back ya estaba listo

2022-12-03 01:09 UTC, closed without merging